apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-platform-backend
  namespace: argocd
  labels:
    managed-by: gitops-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.samsungds.net/infra-team/gitops-manifests.git
    targetRevision: main
    path: platform/backend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-platform-frontend
  namespace: argocd
  labels:
    managed-by: gitops-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.samsungds.net/infra-team/gitops-manifests.git
    targetRevision: main
    path: platform/frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
