{{- if .Values.externalSecret.enabled }}
{{- $targetName := .Values.externalSecret.target.name | default (printf "%s-secrets" .Values.serviceName) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.serviceName }}-external-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/part-of: {{ .Values.tenantId }}
    team: {{ .Values.team | default .Values.tenantId }}
    managed-by: gitops-platform
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: {{ $targetName }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
