apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/part-of: {{ .Values.tenantId }}
    team: {{ .Values.team | default .Values.tenantId }}
    env: {{ .Values.environment }}
    managed-by: gitops-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName }}
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
