{{- if .Values.serviceAccount.create }}
{{- $saName := .Values.serviceAccount.name | default .Values.serviceName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/part-of: {{ .Values.tenantId }}
    team: {{ .Values.team | default .Values.tenantId }}
    managed-by: gitops-platform
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
